FROM python:3.11.9-slim-bullseye

# set work directory
WORKDIR /basic_server

# set environment variables
ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1

# Install Packages
RUN apt-get -y update && apt-get -y install nano

# Install Requirements
COPY ./docker/requirements.txt .
RUN pip install -r requirements.txt